; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
board_build.partitions = huge_app.csv
framework = arduino
upload_port = COM3
monitor_speed = 115200
lib_deps =
	bblanchon/ArduinoJson@^6.17.2
	marvinroger/AsyncMqttClient@^0.9.0
	pkerspe/ESP-FlexyStepper@^1.4.5
	tzapu/WiFiManager@^2.0.17
	esp32async/ESPAsyncWebServer@^3.6.0
	esp32async/AsyncTCP@^3.4.0
	h2zero/NimBLE-Arduino@^1.4.1






